### ISSUE TITLE
`load_bankmarketing` no longer works

### ISSUE THREAD

**Issue by alexsieusahai** [albahnsen/CostSensitiveClassification#14]
Tried on a fresh installation. I think it's because sklearn changed their interface for a couple things; should just be a quick swap. I'll clone the package and attempt to fix it. 

**To Reproduce:**  
`python3 -m virtualenv venv`
`source venv/bin/activate`
`pip3 install costcla`

```
from costcla.datasets import load_bankmarketing
load_bankmarketing()
```

The traceback is

```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from costcla.datasets import load_bankmarketing
  File "/home/alex/test/venv/lib/python3.6/site-packages/costcla/__init__.py", line 31, in <module>
    from .models import *
  File "/home/alex/test/venv/lib/python3.6/site-packages/costcla/models/__init__.py", line 11, in <module>
    from .cost_ensemble import CostSensitivePastingClassifier
  File "/home/alex/test/venv/lib/python3.6/site-packages/costcla/models/cost_ensemble.py", line 8, in <module>
    from sklearn.cross_validation import train_test_split
ModuleNotFoundError: No module named 'sklearn.cross_validation'

```

**Comment by alexsieusahai** [comment]
Oh, I see you've made that change; that's strange; did you upload the changed version to PyPi?

**Comment by albahnsen** [comment]
Done. Sorry for the delay
